Modified the `add_enums` to avoid collisions
OALabs/hashdb-ida pull request #27
Opened 2021-11-05 10:45 UTC by anthonyprintup

- `add_enums` now takes one additional argument which has the default value of `hdb`,
- if the suffix isn't empty it's appended to the `member_name`.

*fixes #23*

2021-11-05 17:03 UTC, herrcore requested changes
Two issues here;

1. We should only be adding a suffix to API names not to all strings. The goal is to avoid clobbering existing types and adding a suffix to regular strings may be confusing to the user.  I think the suffix add has to happen elsewhere in the code or we need to pass a string type to the add_enums function so we can differentiate APIs and strings.

2. I would like to use the accepted IDA convention for conflicting names and using a numeric suffix starting at 0. Since this is the accepted convention for de-conflicting names in IDA other plugins will expect it (for example. FLARE). If we use our own custom suffix it will break stuff (struct_typer).

2021-11-09 19:38 UTC, herrcore commented
Looks like (1) is handled nicely here but not (2) (ref https://github.com/OALabs/hashdb-ida/pull/27#pullrequestreview-799133087)

I think it would be best to pass in an `is_api` flag to `add_enums` which could be used to decide when to use a suffix and when not to? Open to other suggestions though.

2021-11-10 02:27 UTC, anthonyprintup commented
I think that deciding if a suffix should be used based on if the hash is an API is unnecessary because we have to check if a name is taken either way. Each hash value in the hash list would have to be accompanied by `is_api` to avoid any shenanigans.

2021-11-10 04:40 UTC, herrcore reviewed
Ok let's give this a shot

2021-11-10 04:40 UTC, merged